import { test } from 'node:test';
import assert from 'node:assert/strict';

import { parseDiff, type FileDiff } from '../src/parse';
import {
  DEFAULT_MAX_FILES,
  buildPatch,
  buildRequest,
  chunkFiles,
  describeFailure,
  parseBatch,
  skipReason,
  tidy,
  type ChildError,
} from '../src/explain';
import { buildView, wrapText } from '../src/view';
import { notesToMarkdown, newNote, type Summary } from '../src/state';

const file = (raw: string): FileDiff => parseDiff(raw)[0]!;

const SIMPLE = `diff --git a/src/a.ts b/src/a.ts
--- a/src/a.ts
+++ b/src/a.ts
@@ -1,2 +1,2 @@ header
 const a = 1;
-const b = 2;
+const b = 3;
`;

test('generated files are not worth a request', () => {
  const lock = (path: string) =>
    file(`diff --git a/${path} b/${path}\n--- a/${path}\n+++ b/${path}\n@@ -1 +1 @@\n-a\n+b\n`);
  assert.equal(skipReason(lock('package-lock.json')), 'generated');
  assert.equal(skipReason(lock('sub/dir/yarn.lock')), 'generated');
  assert.equal(skipReason(lock('go.sum')), 'generated');
  assert.equal(skipReason(lock('dist/bundle.js')), 'generated');
  assert.equal(skipReason(lock('vendor/lib/x.go')), 'generated');
  assert.equal(skipReason(lock('app.min.js')), 'generated');
  assert.equal(skipReason(lock('__snapshots__/x.snap')), 'generated');
  assert.equal(skipReason(lock('src/lockfile.ts')), null);
  assert.equal(skipReason(lock('src/a.ts')), null);
});

test('binary and content-free files are skipped', () => {
  const binary = file(`diff --git a/i.png b/i.png
index 1..2 100644
Binary files a/i.png and b/i.png differ
`);
  assert.equal(skipReason(binary), 'binary');

  const modeOnly = file(`diff --git a/s.sh b/s.sh
old mode 100644
new mode 100755
`);
  assert.equal(skipReason(modeOnly), 'no-change');
});

test('the patch handed to the model is a valid unified diff', () => {
  const patch = buildPatch(file(SIMPLE));
  assert.equal(
    patch,
    ['--- a/src/a.ts', '+++ b/src/a.ts', '@@ -1,2 +1,2 @@ header', ' const a = 1;', '-const b = 2;', '+const b = 3;'].join('\n'),
  );
});

test('whatever comes back is reduced to one clean line', () => {
  assert.equal(tidy('  Adds a null check.\n\n'), 'Adds a null check.');
  assert.equal(tidy('"Adds a null check."'), 'Adds a null check.');
  assert.equal(tidy('Adds a check.\n```ts\ncode\n```\n'), 'Adds a check.');
  assert.equal(tidy('one\ntwo   three'), 'one two three');
  assert.equal(tidy(''), '');
  const long = tidy('x'.repeat(400));
  assert.equal(long.length, 238);
  assert.ok(long.endsWith('…'));
});

test('wrapping breaks on words and never loses any', () => {
  const text = 'Replaces stub token validation with constant-time HMAC verification.';
  const lines = wrapText(text, 24);
  assert.ok(lines.every((l) => l.length <= 24));
  assert.equal(lines.join(' '), text);
  // Too narrow to wrap sensibly: hand it back whole and let the pane clip.
  assert.deepEqual(wrapText(text, 4), [text]);
});

test('a summary is shown above the first hunk, and only for the current patch', () => {
  const f = file(SIMPLE);
  const rows = buildView(f, [], 'split', { summary: 'Bumps b from 2 to 3.', summaryWidth: 60 });
  assert.equal(rows[0]!.t, 'summary');
  assert.equal(rows[0]!.t === 'summary' && rows[0]!.first, true);
  assert.equal(rows.find((r) => r.t === 'hunk') !== undefined, true);
  // No summary passed: the view is exactly as before.
  assert.equal(buildView(f, [], 'split')[0]!.t, 'hunk');
});

test('a summary does not displace the notes woven into the same file', () => {
  const f = file(SIMPLE);
  const notes = [newNote('src/a.ts', 'new', 2, 'why 3?')];
  const rows = buildView(f, notes, 'split', { summary: 'Bumps b.', summaryWidth: 60 });
  assert.equal(rows[0]!.t, 'summary');
  assert.equal(rows.filter((r) => r.t === 'note').length, 1);
});

test('the export labels generated text and keeps it out of your own notes', () => {
  const summaries: Record<string, Summary> = {
    'src/a.ts': { hash: 'h', body: 'Bumps b from 2 to 3.', model: 'test-model', createdAt: 't' },
  };
  const md = notesToMarkdown([newNote('src/a.ts', 'new', 2, 'why 3?')], 'main...theirs', summaries);
  const lines = md.split('\n').filter(Boolean);
  assert.deepEqual(lines, [
    '## Review notes — main...theirs',
    '### `src/a.ts`',
    '> _What changed (generated by test-model):_ Bumps b from 2 to 3.',
    '- **L2** — why 3?',
  ]);

  // A file with only a generated summary still appears.
  assert.ok(notesToMarkdown([], 'x', summaries).includes('Bumps b'));
  assert.equal(notesToMarkdown([], 'x', {}), '');
});


test('a file is only worth a request if it is not generated, binary or empty', () => {
  // On-demand explanation asks exactly one question per file, and this is it.
  const lock = (path: string) =>
    file(`diff --git a/${path} b/${path}\n--- a/${path}\n+++ b/${path}\n@@ -1 +1 @@\n-a\n+b\n`);
  assert.equal(skipReason(lock('src/a.ts')), null);
  assert.equal(skipReason(lock('.java-version')), null); // small is not the same as worthless
  assert.equal(skipReason(lock('package-lock.json')), 'generated');
});

test('files are chunked to stay within a request budget', () => {
  const of = (n: number): FileDiff => ({ ...file(SIMPLE), path: `f${n}.ts` });
  const files = Array.from({ length: 6 }, (_, i) => of(i));
  // A patch costed at 25k chars fits two per 60k request, not three.
  const chunks = chunkFiles(files, () => 'x'.repeat(25_000));
  assert.deepEqual(chunks.map((c) => c.length), [2, 2, 2]);
  // Everything fits in one when it is small.
  assert.equal(chunkFiles(files, () => 'x').length, 1);
  // A single file over budget still gets sent, alone.
  assert.deepEqual(chunkFiles(files.slice(0, 2), () => 'x'.repeat(90_000)).map((c) => c.length), [1, 1]);
  assert.deepEqual(chunkFiles([], () => 'x'), []);
});

test('one request covers every file, each under its own path marker', () => {
  const a: FileDiff = { ...file(SIMPLE), path: 'a.ts' };
  const b: FileDiff = { ...file(SIMPLE), path: 'dir/b.ts' };
  const req = buildRequest([a, b]);
  assert.ok(req.includes('=== FILE: a.ts'));
  assert.ok(req.includes('=== FILE: dir/b.ts'));
  assert.ok(req.indexOf('=== FILE: a.ts') < req.indexOf('=== FILE: dir/b.ts'));
});

test('the reply is read per file, and anything unexpected is dropped', () => {
  const expected = new Set(['a.ts', 'dir/b.ts']);
  const reply = [
    "Here are the summaries:",           // preamble the prompt forbade
    "a.ts\tAdds a null guard before the return.",
    "dir/b.ts\tRenames the field; no behaviour change.",
    "nope.ts\tA file we never asked about.",
    "",                                   // blank line
    "- a bullet without a tab",
    "a.ts\tA second summary for a file already answered.",
  ].join('\n');

  const got = parseBatch(reply, expected);
  assert.deepEqual([...got.entries()], [
    ['a.ts', 'Adds a null guard before the return.'],
    ['dir/b.ts', 'Renames the field; no behaviour change.'],
  ]);
});

test('a quoted or padded path still matches, and an empty summary does not', () => {
  const expected = new Set(['a.ts']);
  assert.equal(parseBatch('  "a.ts" \tQuoted by the model.', expected).get('a.ts'), 'Quoted by the model.');
  assert.equal(parseBatch('a.ts\t   ', expected).size, 0);
  assert.equal(parseBatch('a.ts', expected).size, 0);      // no tab at all
  assert.equal(parseBatch('\tno path', expected).size, 0);  // tab at position 0
});

test('a failure is described by its cause, never by the command line', () => {
  // Node's message for a failed child is `Command failed: <argv>`, and our argv
  // holds the whole prompt — putting it in a status bar makes it unreadable.
  const nodeMessage = 'Command failed: claude -p You are helping someone review a pull request...';
  const childError = (extra: Partial<ChildError>): ChildError =>
    Object.assign(new Error(nodeMessage), extra) as ChildError;

  // A timeout: killed with SIGTERM and usually no stderr at all. This is the
  // failure most likely to happen, so it must be the clearest.
  assert.match(
    describeFailure(childError({ killed: true, signal: 'SIGTERM' }), ''),
    /^no reply within \d+s$/,
  );

  // Real stderr is the best explanation available.
  assert.equal(
    describeFailure(childError({ code: 1 }), 'Credit balance too low\nat foo()'),
    'Credit balance too low',
  );

  // A non-zero exit with nothing on stderr: say the code rather than the argv.
  assert.equal(
    describeFailure(childError({ code: 3 }), ''),
    'claude exited with code 3',
  );
  assert.equal(describeFailure(childError({}), '   \n  '), 'claude failed with no output');

  // Whatever happens, the prompt never reaches the user.
  for (const stderr of ['', 'boom', '\n\n']) {
    for (const err of [{ killed: true, signal: 'SIGTERM' }, { code: 2 }, {}] as Array<Partial<ChildError>>) {
      const out = describeFailure(childError(err), stderr);
      assert.ok(!out.includes('Command failed'), out);
      assert.ok(!out.includes('helping someone'), out);
      assert.ok(out.length < 120, out);
    }
  }
});

test('the cap is reported, not silently applied', () => {
  // The failure this guards against: a 58-file branch under a cap of 40 left
  // 18 files with no summary, no message and nothing logged — which looks
  // exactly like the tool not working.
  const many = Array.from({ length: 58 }, (_, i): FileDiff => ({ ...file(SIMPLE), path: `f${i}.ts` }));
  const candidates = many.filter((f) => !skipReason(f));
  assert.equal(candidates.length, 58);
  // Nothing about a cap of 40 is visible from the file list alone; the runner
  // has to hand back the shortfall for anyone to know.
  const cap = 40;
  assert.equal(candidates.length - candidates.slice(0, cap).length, 18);
});

test('the default cap is a runaway guard, not a per-review budget', () => {
  // Batching made cost per chunk rather than per file, so a cap low enough to
  // truncate an ordinary branch is a bug source, not a saving.
  assert.ok(DEFAULT_MAX_FILES >= 100, `cap of ${DEFAULT_MAX_FILES} would truncate ordinary branches`);
});
